🔥  Feature/store : Get All Components Together 🥇
roniy68/spaceX pull request #32
Opened 2023-03-09 13:24 UTC by roniy68

# Highlights 🥇 

<img src="https://media4.giphy.com/media/l4pTfBQTLOecArqSs/giphy.gif"/>

## What I Have Done: 

✅ Setup React, React-Router, React-Logger
✅ Add Redux Store
✅ Add Missions , Rockets, [ TO THE PROFILE ]
✅ Add Main Canvas 
✅ Add Live Deploy
✅ BootStrap Add

# [Live Here](https://6409ddabc88f080394d0b31f--ahr-spacex.netlify.app/) 
## Why
🔴 Check if any error with setup 
🔴 Suggest Any other ideas

### Changes details
***Please add @roniy68 in your comment so that I get notified***
## Missed anything?
- [ ] Explained the purpose of this PR.
- [ ] Self reviewed the PR.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
-  Followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
-  Followed our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

2023-03-09 13:55 UTC, roniy68 commented
# ♻️ Please Ignore The Merge Conflict 🌀 
---

## It will resolve automatically after merging to development 😄

2023-03-10 08:00 UTC, Victor-chiemerie requested changes
👋 Hi @roniy68

Great job so far!
Your project is looking fantastic 👍 

However, there's a little you need to make on this project

<img src="https://media4.giphy.com/media/QW9DYS2fsdORhO9Phu/giphy.gif"/>

## Highlights 🥇 

React redux used ✔️ 
APIs connected ✔️ 
No Linters error ✔️ 
Best practices for HTML and CSS ✔️ 
Best practices for JavaScript ✔️ 
Documented in a professional way ✔️ 

# Required Changes ♻️ 

check the comments under the review

# Optional Suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**


As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-10 08:00 UTC, Victor-chiemerie commented on src/App.js
> -          <Route path="*" element={<NotFound />} />
👍  Excellent work on how you dispatch the `fetchRockets` action on the initial loading of the page, but I would suggest that you restore the file `NotFound` to present a page to the user when an error URL is typed.

2023-03-10 08:00 UTC, Victor-chiemerie commented on src/components/Missions/Missions.jsx
> +import Button from 'react-bootstrap/Button';
✔️ your use of this react-bootstrap is an excellent work practice, I would love to learn that from you.

2023-03-10 08:05 UTC, roniy68 commented on src/App.js
> -          <Route path="*" element={<NotFound />} />
👍  May be we can add the Not Found page later

2023-03-10 08:05 UTC, roniy68 commented
# 😄 Thanks for your Review

2023-03-10 08:11 UTC, merged